# Generated by Django 3.1.14 on 2022-12-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20220109_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='id',
        ),
        migrations.AddField(
            model_name='userpost',
            name='post_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
