# Generated by Django 3.1.14 on 2022-12-17 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20221208_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='post_id',
        ),
        migrations.AddField(
            model_name='userpost',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
